name: CI
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.0